# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-19 03:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suplier', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suplier',
            name='status',
            field=models.CharField(choices=[('0', 'AKTIF'), ('1', 'TIDAK AKTIF')], default='0', max_length=6),
        ),
    ]
