# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-18 04:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('barang', '0001_initial'),
        ('satuan', '0001_initial'),
        ('jual', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bjual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hargaModal', models.CharField(max_length=15)),
                ('hargaJual', models.CharField(max_length=15)),
                ('jumlahJual', models.CharField(max_length=15)),
                ('pilihan', models.CharField(max_length=15)),
                ('barang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barang.Barang')),
                ('jual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jual.Jual')),
                ('satuan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='satuan.Satuan')),
            ],
        ),
    ]
