# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-24 02:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bjual', '0002_auto_20170802_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='bjual',
            name='hargalain',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
