# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-24 03:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bjual', '0003_bjual_hargalain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bjual',
            name='hargalain',
            field=models.CharField(blank=True, default=0, max_length=12, null=True),
        ),
    ]
