# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-18 02:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kategori', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Barang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kodeBarang', models.CharField(max_length=15, verbose_name='KODE BARANG')),
                ('namaBarang', models.CharField(max_length=45, verbose_name='NAMA BARANG')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('kategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kategori.Kategori', verbose_name='KATEGORI')),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
