# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-14 03:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bjual', '0002_auto_20170802_0932'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rjual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('jumlah', models.IntegerField()),
                ('pilihan', models.CharField(choices=[('0', 'KEMBALI KE STOK'), ('1', 'MUSNAHKAN BARANG')], default='0', max_length=15)),
                ('keterangan', models.TextField(null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('bjual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bjual.Bjual')),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
