# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-18 04:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('barang', '0001_initial'),
        ('satuan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stok',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stok', models.CharField(max_length=12)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('barang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barang.Barang')),
                ('satuan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='satuan.Satuan')),
            ],
        ),
    ]
