# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-19 01:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekstrakstok', '0002_ekstrakstok_satuan'),
    ]

    operations = [
        migrations.AddField(
            model_name='ekstrakstok',
            name='sisa',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
