# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-22 07:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekstrakstok', '0003_ekstrakstok_sisa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ekstrakstok',
            name='keterangan',
            field=models.TextField(blank=True, null=True),
        ),
    ]
