# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-18 03:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('suplier', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Masuk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(verbose_name='TANGGAL')),
                ('nota', models.CharField(max_length=15, verbose_name='NO NOTA')),
                ('sales', models.CharField(max_length=50, verbose_name='NAMA SALES')),
                ('pembayaran', models.CharField(choices=[('0', 'HUTANG'), ('1', 'LUNAS')], default='1', max_length=6)),
                ('jangkaWaktu', models.CharField(max_length=250, verbose_name='JANGKA WAKTU')),
                ('status', models.CharField(max_length=15)),
                ('keterangan', models.TextField(null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('suplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suplier.Suplier', verbose_name='SUPLIER')),
            ],
        ),
    ]
