# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-24 07:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masuk', '0002_auto_20170720_0310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masuk',
            name='status',
            field=models.CharField(blank=True, default=0, max_length=15),
        ),
    ]
