# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-08 03:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masuk', '0003_auto_20170724_0759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masuk',
            name='status',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
