# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-31 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jual', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jual',
            name='keterangan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jual',
            name='namaPembeli',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='NAMA PEMBELI'),
        ),
        migrations.AlterField(
            model_name='jual',
            name='pembayaran',
            field=models.CharField(blank=True, choices=[('0', 'HUTANG'), ('1', 'LUNAS')], default='1', max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='jual',
            name='potongan',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='jual',
            name='statusPembeli',
            field=models.CharField(blank=True, choices=[('0', 'LANGGANAN'), ('1', 'BUKAN LANGGANAN')], default='0', max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='jual',
            name='tanggal',
            field=models.DateField(blank=True, null=True),
        ),
    ]
