# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-02 09:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jual', '0002_auto_20170731_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jual',
            name='pembayaran',
            field=models.CharField(blank=True, choices=[('0', 'HUTANG'), ('1', 'LUNAS')], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='jual',
            name='posted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='jual',
            name='potongan',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
