# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-07 06:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jual', '0003_auto_20170802_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jual',
            name='pembayaran',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='jual',
            name='potongan',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
