# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-07 06:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jual', '0004_auto_20170807_0621'),
    ]

    operations = [
        migrations.AddField(
            model_name='jual',
            name='bayar',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='jual',
            name='pembayaran',
            field=models.CharField(blank=True, choices=[('0', 'HUTANG'), ('1', 'LUNAS')], max_length=6, null=True),
        ),
    ]
