# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-08 03:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jual', '0005_auto_20170807_0621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jual',
            name='bayar',
            field=models.CharField(blank=True, default=0, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='jual',
            name='keterangan',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
