# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-22 07:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jual', '0007_auto_20170814_0351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jual',
            name='potongan',
            field=models.CharField(blank=True, default=0, max_length=8, null=True),
        ),
    ]
