# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-24 07:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masuk', '0002_auto_20170720_0310'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Butang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('penerima', models.CharField(max_length=25)),
                ('jumlahHutang', models.IntegerField()),
                ('jumlahBayar', models.IntegerField()),
                ('sisaHutang', models.IntegerField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('masuk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masuk.Masuk')),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
