# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-25 01:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('butang', '0002_auto_20170724_1011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='butang',
            name='sisaHutang',
        ),
    ]
