# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-18 03:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masuk', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Biaya',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namaBiaya', models.CharField(max_length=100, verbose_name='NAMA BIAYA')),
                ('jumlahBiaya', models.CharField(max_length=15)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('masuk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masuk.Masuk')),
            ],
        ),
    ]
