# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-19 03:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kategori', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kategori',
            name='posted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
