# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-09 07:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kategori', '0002_auto_20170719_0319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kategori',
            name='namaKategori',
            field=models.CharField(max_length=25, verbose_name='NAMA KATEGORI'),
        ),
    ]
