# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-20 03:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmasuk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bmasuk',
            name='jumlah',
            field=models.IntegerField(),
        ),
    ]
