# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-11 09:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmasuk', '0002_auto_20170720_0310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bmasuk',
            name='harga',
            field=models.IntegerField(),
        ),
    ]
