# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-18 04:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bmasuk', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rmasuk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlahRetur', models.CharField(max_length=15)),
                ('keterangan', models.TextField(null=True)),
                ('rmasukStatus', models.CharField(max_length=15)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('bmasuk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bmasuk.Bmasuk')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
