# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-28 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rmasuk', '0002_auto_20170728_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rmasuk',
            name='rmasukStatus',
            field=models.IntegerField(),
        ),
    ]
