# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-28 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rmasuk', '0003_auto_20170728_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rmasuk',
            name='jumlahRetur',
            field=models.IntegerField(),
        ),
    ]
