# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-28 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rmasuk', '0005_auto_20170728_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rmasuk',
            name='rmasukStatus',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
