# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-28 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rmasuk', '0006_auto_20170728_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rmasuk',
            name='rmasukStatus',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
